---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_reload:
      host: "{{ ansible_ssh_host }}"
      username: root
      password: lab
      location: "0/RP0/CPU0"
      force: True
    register: src
  - debug: var=src.stdout_lines
