---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars_files:
  - 'vars/iosxr_vars.yml'

  tasks:
  - iosxr_rollback:
      host: "{{ ansible_host }}"
      username: '{{ iosxr_username }}'
      password: '{{ iosxr_password }}'
      last_n_committed: 1
      #rollback_id: 1000000016
      #to_rollback_id: 1000000017
      #to_exclude_rollback_id: 1000000018
    register: output
  - debug: var=output.stdout_lines
