---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: get system facts
    iosxr_get_facts:
      host: "{{ ansible_ssh_host }}"
      username: root
      password: lab
    register: facts
  - debug: var=facts
