---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: remove user aermongk
    iosxr_config:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      commands: 'no username aermongk'
      force: True
    register: output
  - debug: var=output.updates
