---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars_files:
  - 'vars/iosxr_vars.yml'

  tasks:
  - name: clear log data
    iosxr_clear_log:
      host: '{{ ansible_host }}'
      username: '{{ iosxr_username }}'
      password: '{{ iosxr_password }}'
    register: output
  - debug: var=output.stdout_lines
