---
- hosts: ss-xr
  connection: local
  gather_facts: no
  vars:
    smu_name: "xrv9k-ospf-1.0.0.0-r60125I"
    user: root
    passwd: lab

  tasks:
  - name: deactivate SMU package
    iosxr_install_package:
      host: "{{ ansible_ssh_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      pkgname: "{{ smu_name }}"
      state: deactivate
    register: output
  - debug: var=output.stdout_lines

  - name: remove SMU package
    iosxr_install_package:
      host: "{{ ansible_ssh_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      pkgname: "{{ smu_name }}"
      state: absent
    register: output
  - debug: var=output.stdout_lines
