---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: clear log data
    iosxr_clear_log:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
    register: output
  - debug: var=output.stdout_lines
