---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_cli:
      host: "{{ ansible_ssh_host }}"
      username: root
      password: lab
      command: "{{ cmd }}"
    register: output
  - debug: var=output.stdout_lines
