---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_rollback:
      host: "{{ ansible_ssh_host }}"
      last_n_committed: 1
    register: src
  - debug: var=src.stdout_lines
