---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    smu_name: 'xrv9k-mpls-2.0.0.1-r60204I.CSCxr33333'

  tasks:
  - name: update SMU package
    iosxr_install_package:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      pkgpath: 'https://aermongk-dev/'
      pkgname: '{{ smu_name }}'
      state: update
    register: output
  - debug: var=output.stdout_lines
