---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars_files:
  - 'vars/iosxr_vars.yml'

  vars_prompt:
  - name: yesno
    prompt: 'Are you sure you want to reload the router (yes/no)? '

  tasks:
  - iosxr_reload:
      host: '{{ ansible_host }}'
      username: '{{ iosxr_username }}'
      password: '{{ iosxr_password }}'
      confirm: '{{ yesno }}'
      location: '0/RP0/CPU0'
      force: True
    register: output
  - debug: var=output.stdout_lines
