---
- hosts: ss-xr
  connection: local
  gather_facts: no
  vars_files:
  - 'vars/iosxr_vars.yml'

  vars:
    smu_name: 'xrv9k-ospf-1.0.0.0-r60125I'

  tasks:
  - name: add SMU package
    iosxr_install_package:
      host: '{{ ansible_host }}'
      username: '{{ iosxr_username }}'
      password: '{{ iosxr_password }}'
      pkgpath: 'tftp://192.168.1.1'
      pkgname: '{{ smu_name }}'
      state: present
    register: output
  - debug: var=output.stdout_lines

  - name: activate SMU package
    iosxr_install_package:
      host: '{{ ansible_host }}'
      username: '{{ iosxr_username }}'
      password: '{{ iosxr_password }}'
      pkgname: '{{ smu_name }}'
      state: activate
    register: output
  - debug: var=output.stdout_lines
