---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: remove user aermongk
    iosxr_config:
      host: '{{ ansible_ssh_host }}'
      username: root
      password: lab
      commands: 'no username aermongk'
    register: output
  - debug: var=output.updates
