---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_show_install_request:
      host: "{{ ansible_ssh_host }}"
      username: root
      password: lab
    register: output
  - debug: var=output.stdout_lines
