---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_command:
      commands: "show running-config"
      host: "{{ ansible_ssh_host }}"
      username: root
      password: lab
    register: output
  - debug: var=output.stdout_lines
