---
- hosts: ss-xr
  gather_facts: no
  vars:
    smu_name: 'xrv9k-ospf-1.0.0.0-r60201I'

  tasks:
  - name: add SMU package
    iosxr_install_package:
      username: '{{ ansible_ssh_user }}'
      pkgpath: 'tftp://192.168.1.1'
      pkgname: '{{ smu_name }}'
      state: present
    register: output
  - debug: var=output.stdout_lines

  - name: activate SMU package
    iosxr_install_package:
      username: '{{ ansible_ssh_user }}'
      pkgname: '{{ smu_name }}'
      state: activated
    register: output
  - debug: var=output.stdout_lines
