---
- hosts: ss-xr
  gather_facts: no

  vars_prompt:
    - name: yesno
      prompt: "Are you sure you want to reload the router (yes/no)? "

  tasks:
  - iosxr_reload:
      confirm: "{{ yesno }}"
      force: True
    register: output
  - debug: var=output.stdout_lines
